// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpcvuQV8Cv_4HmClGd04qk2AIYFQgtszw',
    appId: '1:861460921184:web:297b55342721c0d391fc05',
    messagingSenderId: '861460921184',
    projectId: 'safety-driving-237a7',
    authDomain: 'safety-driving-237a7.firebaseapp.com',
    storageBucket: 'safety-driving-237a7.appspot.com',
    measurementId: 'G-N7NYMH0014',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMiqDAdLNOv9-XbZpN98bf6wv8MpebS4s',
    appId: '1:861460921184:android:1697a0364b3813e991fc05',
    messagingSenderId: '861460921184',
    projectId: 'safety-driving-237a7',
    storageBucket: 'safety-driving-237a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBleADCy7plrRer6_3nlbCihHpe8G94qQ0',
    appId: '1:861460921184:ios:6b58fd27527621cc91fc05',
    messagingSenderId: '861460921184',
    projectId: 'safety-driving-237a7',
    storageBucket: 'safety-driving-237a7.appspot.com',
    iosClientId: '861460921184-kg0ur8ef876p5cdo758onorahqp300hp.apps.googleusercontent.com',
    iosBundleId: 'com.example.safe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBleADCy7plrRer6_3nlbCihHpe8G94qQ0',
    appId: '1:861460921184:ios:6b58fd27527621cc91fc05',
    messagingSenderId: '861460921184',
    projectId: 'safety-driving-237a7',
    storageBucket: 'safety-driving-237a7.appspot.com',
    iosClientId: '861460921184-kg0ur8ef876p5cdo758onorahqp300hp.apps.googleusercontent.com',
    iosBundleId: 'com.example.safe',
  );
}
